#!/bin/bash

CONF_DIR="$(dirname "$0")/configs"

source "$CONF_DIR/toolchain.conf"
source "$CONF_DIR/sdk.conf"
source "$CONF_DIR/atf.conf"
source "$CONF_DIR/zephyr.conf"
source "$CONF_DIR/sdimage.conf"
source "$CONF_DIR/simics.conf"
source "$CONF_DIR/uboot.conf"