########################################
# ATF
########################################
ATF_REPO_URL="https://github.com/altera-opensource/arm-trusted-firmware"
ATF_BRANCH="QPDS24.3_REL_GSRD_PR"
ATF_PLAT="agilex5"