########################################
# SD IMAGE SCRIPT
########################################
SDIMAGE_SCRIPT_URL="https://releases.rocketboards.org/2023.12/zephyr/gsrd_zephyr/agilex5/cli/sdmmc_boot/make_sdimage.sh"

########################################
# GLOBAL
########################################
WORKDIR="agilex5_zgsrd"
SD_IMAGE_NAME="sdimage.img"