########################################
# U-BOOT
########################################

# Generic upstream U-Boot repo
UBOOT_REPO_URL="https://github.com/u-boot/u-boot"

# Can be:
# - branch (e.g. master, next)
# - tag (e.g. v2024.01)
# - commit hash (e.g. 1a2b3c4d)
UBOOT_REF="v2024.01"

########################################
# OPTIONAL
########################################
BITSTREAM_URL=""