########################################
# ZEPHYR
########################################
# ZEPHYR_REPO_URL="https://github.com/zephyrproject-rtos/zephyr"
# ZEPHYR_BRANCH="v4.3-branch"

ZEPHYR_REPO_URL="https://github.com/Hareemx-Sadiq/zephyr.git"
ZEPHYR_BRANCH="multi_threading_t"

BOARD="intel_socfpga_agilex5_socdk"
APP="samples/multi_threading"